### ISSUE TITLE
Some of the keyboard shortcuts seems not working

### ISSUE THREAD

**Issue by motowizlee** [Akrog/evershort#5]
Hi,

Great work and addition for the Evernote Web Client. Would like to report this issue in hope of improving it more. Below are the issue details, please let me know if you need more details. Thanks!

System: Chrome, Windows 10 x64 Pro

Example of keyboard shortcuts that doesn't seem to work: 

1. 'j' and 'k' works in Notebook list but not in Shortcuts
2. 'l' don't seems to edit note
3. Most of the text editor shortcuts such as "Insert Link", "Divider Line", "Exit note editor" etc does not work. So far only the more universal shortcuts such as "bold", "italic", "underline" are working

**Comment by Akrog** [comment]
Of the 3 issues mentioned the last two are bugs and have been fixed in v0.3.1, but not being able to navigate shortcuts it's a missing feature that cannot be cleanly implemented.

The complication to implement the Shortcut navigation is that we cannot grammatically trigger the mouse hover over the elements because Chrome doesn't trigger default actions (:hover in this case) when we dispatch the event.

I'll open a different issue to track the feature and look for a workaround to implement the feature.

**Comment by motowizlee** [comment]
Thanks @Akrog ! Great to be able to use the editor, in the mean time will just wait for the Shortcut Navigation Fix. 

[Link to the Shortcut Navigation issue](https://github.com/Akrog/evershort/issues/6) just for reference.
